spring:
  application:
    name: DecentrathonTelegramMiniApp

  datasource:
    url: jdbc:postgresql://localhost:5432/clever_coin_database
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot:
    token: 7898613339:AAFYXMm2UJMyB2HvnTce5x4fO_N24W-DfCU
    name: DecentrathonTelegramMiniAppBot
